# Generated by Django 4.2.7 on 2024-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Unityapp", "0005_comment_user_alter_comment_diary_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=280),
        ),
    ]
