# Generated by Django 4.2.7 on 2024-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Unityapp", "0006_alter_comment_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
