# Generated by Django 4.2.7 on 2024-01-27 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Unityapp", "0008_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="chat_room",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
