# Generated by Django 4.2.7 on 2024-02-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Unityapp", "0014_alter_diaryentry_id_alter_yourmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
