# Generated by Django 4.2.7 on 2024-02-06 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Unityapp", "0015_alter_diaryentry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="diary_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="Unityapp.diaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2024, 2, 6, 15, 52, 29, 803004, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="familychatmessage",
            name="user",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2024, 2, 6, 15, 54, 1, 701979, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siblingchatmessage",
            name="user",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2024, 2, 6, 15, 55, 3, 759324, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
