# Generated by Django 4.2.7 on 2024-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Unityapp", "0016_alter_chatmessage_user_alter_comment_diary_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
